GET http://localhost:5000/data

###
GET http://localhost:5000/data/1

###
POST http://localhost:5000/data
Content-Type: application/json

{
    "name": "aing",
    "bahasa": "Javascript",
    "error" : "not defind",
    "penyebab": "ada variabel yang tidak di definisikan",
    "solusi": "cek kodemu, mungkin ada variabel yang belum kamu deklrasikan"
}

