GET http://localhost:5000/data

###
GET http://localhost:5000/data/1

###
GET https://temanngoding-backend-production.up.railway.app/data/


###
POST http://localhost:5000/data
Content-Type: application/json

{
    "name": "aing",
    "bahasa": "Javascript",
    "error" : "not defind",
    "penyebab": "ada variabel yang tidak di definisikan",
    "solusi": "cek kodemu, mungkin ada variabel yang belum kamu deklrasikan"
}


###
DELETE https://temanngoding-backend-production.up.railway.app/data/63da95bf3c85808762a876cb
